build:
	@spm build

deploy:
	@rm -rf ../sea-modules/wolf-app/vehicle-mgmt
	@mkdir -p ../sea-modules/wolf-app/vehicle-mgmt
	@mkdir -p ../sea-modules/wolf-app/vehicle-mgmt/0.0.1
	@cp     dist/*.* ../sea-modules/wolf-app/vehicle-mgmt/0.0.1
	@echo
	@echo   " deploy to sea-modules/wolf-app/vehcile-mgmt/0.0.1"
	@echo
