
build:
	@spm build

deploy:
	@rm -rf ../sea-modules/wolf-app/vehicle-mgmt
	@mkdir -p ../sea-modules/wolf-app/vehicle-mgmt
	@mkdir  ../sea-modules/wolf-app/vehicle-mgmt/0.0.1
	@cp     dist/*.* ../sea-modules/wolf-app/vehicle-mgmt/0.0.1
	@echo
	@echo   "----------------------------------------------------"
	@echo   "| Success To Deploy seajs-modules/wolf-app/vehicle-mgmt|"
	@echo   "----------------------------------------------------"
	@echo
