language: node_js
node_js:
  - '0.10'
notifications:
  email:
    - tang.jilong@gmail.com
    - kkiiiu@gmail.com
before_script:
  - npm install -g grunt-cli
script:
  - make build
#after_scipt:
#  - grunt doc
branches:
  only:
    - master
