
build:
	@spm build

deploy:
	@rm -rf ../sea-modules/wolf-app/user-group-mgmt
	@mkdir -p ../sea-modules/wolf-app/user-group-mgmt
	@mkdir  ../sea-modules/wolf-app/user-group-mgmt/0.0.1
	@cp     dist/*.* ../sea-modules/wolf-app/user-group-mgmt/0.0.1
	@echo
	@echo   "-- Success To Deploy seajs-modules/wolf-app/user-group-mgmt --"
	@echo
