
build:
	@spm build

deploy:
	@rm -rf ../sea-modules/wolf-app/generic-filter
	@mkdir -p ../sea-modules/wolf-app/generic-filter
	@mkdir  ../sea-modules/wolf-app/generic-filter/0.0.1
	@cp     dist/*.* ../sea-modules/wolf-app/generic-filter/0.0.1
	@echo
	@echo   "-- Success To Deploy seajs-modules/wolf-app/generic-filter --"
	@echo
