
build:
	@spm build

deploy:
	@rm -rf ../sea-modules/wolf-app/app-main
	@mkdir -p ../sea-modules/wolf-app/app-main
	@mkdir  ../sea-modules/wolf-app/app-main/0.0.1
	@cp     dist/*.* ../sea-modules/wolf-app/app-main/0.0.1
	@echo
	@echo   "----------------------------------------------------"
	@echo   "| Success To Deploy seajs-modules/wolf-app/app-main|"
	@echo   "----------------------------------------------------"
	@echo
