
build:
	@spm build

deploy:
	@rm -rf ../sea-modules/wolf-app/role-mgmt
	@mkdir -p ../sea-modules/wolf-app/role-mgmt
	@mkdir  ../sea-modules/wolf-app/role-mgmt/0.0.1
	@cp     dist/*.* ../sea-modules/wolf-app/role-mgmt/0.0.1
	@echo
	@echo   "-----------------------------------------------------"
	@echo   "| Success To Deploy seajs-modules/wolf-app/role-mgmt|"
	@echo   "-----------------------------------------------------"
	@echo
