
build:
	@spm build

deploy:
	@rm -rf ../sea-modules/wolf-app/layout
	@mkdir -p ../sea-modules/wolf-app/layout
	@mkdir  ../sea-modules/wolf-app/layout/0.0.1
	@cp     dist/*.* ../sea-modules/wolf-app/layout/0.0.1
	@echo
	@echo   "--------------------------------------------------"
	@echo   "| Success To Deploy seajs-modules/wolf-app/layout|"
	@echo   "--------------------------------------------------"
	@echo
