
build:
	@spm build

deploy:
	@rm -rf ../sea-modules/wolf-app/security
	@mkdir -p ../sea-modules/wolf-app/security
	@mkdir  ../sea-modules/wolf-app/security/0.0.1
	@cp     dist/*.* ../sea-modules/wolf-app/security/0.0.1
	@echo
	@echo   "-- Success To Deploy seajs-modules/wolf-app/security --"
	@echo
