
build:
	@spm build

deploy:
	@rm -rf ../sea-modules/wolf-app/dashboard
	@mkdir -p ../sea-modules/wolf-app/dashboard
	@mkdir  ../sea-modules/wolf-app/dashboard/0.0.1
	@cp     dist/*.* ../sea-modules/wolf-app/dashboard/0.0.1
	@echo
	@echo   "-- Success To Deploy seajs-modules/wolf-app/dashboard --"
	@echo
