
build:
	@spm build

deploy:
	@rm -rf ../sea-modules/wolf-app/app-common
	@mkdir -p ../sea-modules/wolf-app/app-common
	@mkdir  ../sea-modules/wolf-app/app-common/0.0.1
	@cp     dist/*.* ../sea-modules/wolf-app/app-common/0.0.1
	@echo
	@echo   "-- Success To Deploy seajs-modules/wolf-app/app-common --"
	@echo
